version: '3.1'

services:
  db:
    image: postgres:14
    container_name: postgres_container
    build:
      context: .
      dockerfile: Dockerfile
      target: db
    restart: unless-stopped
    env_file:
      - .env
    volumes: 
      - ./dbdata:/var/lib/postgresql/data
      - ./docker-initdb:/docker-entrypoint-initdb.d
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      timeout: 45s
      interval: 10s
      retries: 10
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:7.2
    env_file:
      - .env
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres

volumes:
  pgadmin-data:

networks:
  postgres:
    driver: bridge