CREATE TABLE amenities (
	id SERIAL PRIMARY KEY,
	name TEXT NOT NULL
);

CREATE TABLE users (
	id SERIAL PRIMARY KEY,
	username TEXT NOT NULL
);

CREATE TABLE reservations (
	id SERIAL PRIMARY KEY,
	amenityId INTEGER NOT NULL,
	userId INTEGER NOT NULL,
	startTime INTEGER NOT NULL DEFAULT 0,
	endTime INTEGER NOT NULL DEFAULT 0,
	date BIGINT NOT NULL,
	CONSTRAINT fk_reservation_id FOREIGN KEY (amenityId) REFERENCES amenity (id)
);
